# Generated by Django 4.2.6 on 2023-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_celular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paleta',
        ),
        migrations.AddField(
            model_name='celular',
            name='modelo',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
