# Generated by Django 4.2.6 on 2023-10-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_tablets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celular',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
