# Generated by Django 4.2.6 on 2023-10-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_celular_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Tablets',
        ),
    ]
