# Generated by Django 4.2.6 on 2023-10-31 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_accesorio_alter_tablet_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesorio',
            old_name='producto',
            new_name='tipo_producto',
        ),
    ]
